<?php
$QUERY_SOMA_AQUITAR = mysqli_query($CONNECTIONFATURAMENTO, "SELECT SUM(Qtd_conf) AS SQUANTIDADE FROM tb_ordem_venda WHERE col_TipoOV='Venda Representante' AND UM='10' AND SAFRA='$SAFRA';");
$COSULTORADQUIT = mysqli_num_rows($QUERY_SOMA_AQUITAR);
if($COSULTORADQUIT > 0){
    while ($Linha = $QUERY_SOMA_AQUITAR->fetch_array()){
        if ($row['UNIDADE']=='KG') {
            $QTDOVKG_SEMANA_AQUITAR = $Linha['SQUANTIDADE']/50;
        }else{
            $QTDOVSC_SEMANA_AQUITAR = $Linha['SQUANTIDADE'];
        }
    }
}
$RESULTADO_SEMANA_AQUITAR = 
$QTDOVKG_SEMANA_AQUITAR +
$QTDOVSC_SEMANA_AQUITAR +
$QTDCONTRATO40000_SEMANA_AQUITAR+
$QTDCONTRATO40001_SEMANA_AQUITAR+
$QTDCONTRATO40002_SEMANA_AQUITAR+
$QTDCONTRATO40003_SEMANA_AQUITAR+
$QTDCONTRATO40004_SEMANA_AQUITAR+
$QTDCONTRATO40005_SEMANA_AQUITAR+
$QTDCONTRATO40006_SEMANA_AQUITAR+
$QTDCONTRATO40007_SEMANA_AQUITAR+
$QTDCONTRATO40008_SEMANA_AQUITAR+
$QTDCONTRATO40009_SEMANA_AQUITAR+
$QTDCONTRATO40010_SEMANA_AQUITAR+
$QTDCONTRATO40011_SEMANA_AQUITAR+
$QTDCONTRATO40012_SEMANA_AQUITAR+
$QTDCONTRATO40013_SEMANA_AQUITAR+
$QTDCONTRATO40014_SEMANA_AQUITAR+
$QTDCONTRATO40015_SEMANA_AQUITAR+
$QTDCONTRATO40016_SEMANA_AQUITAR+
$QTDCONTRATO40017_SEMANA_AQUITAR+
$QTDCONTRATO40018_SEMANA_AQUITAR+
$QTDCONTRATO40019_SEMANA_AQUITAR+
$QTDCONTRATO40020_SEMANA_AQUITAR+
$QTDCONTRATO40021_SEMANA_AQUITAR+
$QTDCONTRATO40022_SEMANA_AQUITAR+
$QTDCONTRATO40023_SEMANA_AQUITAR+
$QTDCONTRATO40024_SEMANA_AQUITAR+
$QTDCONTRATO40025_SEMANA_AQUITAR+
$QTDCONTRATO40026_SEMANA_AQUITAR+
$QTDCONTRATO40027_SEMANA_AQUITAR+
$QTDCONTRATO40028_SEMANA_AQUITAR+
$QTDCONTRATO40029_SEMANA_AQUITAR+
$QTDCONTRATO40030_SEMANA_AQUITAR+
$QTDCONTRATO40031_SEMANA_AQUITAR+
$QTDCONTRATO40032_SEMANA_AQUITAR+
$QTDCONTRATO40033_SEMANA_AQUITAR+
$QTDCONTRATO40034_SEMANA_AQUITAR+
$QTDCONTRATO40035_SEMANA_AQUITAR+
$QTDCONTRATO40036_SEMANA_AQUITAR+
$QTDCONTRATO40037_SEMANA_AQUITAR+
$QTDCONTRATO40038_SEMANA_AQUITAR+
$QTDCONTRATO40039_SEMANA_AQUITAR+
$QTDCONTRATO40040_SEMANA_AQUITAR+
$QTDCONTRATO40041_SEMANA_AQUITAR+
$QTDCONTRATO40042_SEMANA_AQUITAR+
$QTDCONTRATO40043_SEMANA_AQUITAR+
$QTDCONTRATO40044_SEMANA_AQUITAR+
$QTDCONTRATO40045_SEMANA_AQUITAR+
$QTDCONTRATO40046_SEMANA_AQUITAR+
$QTDCONTRATO40047_SEMANA_AQUITAR+
$QTDCONTRATO40048_SEMANA_AQUITAR+
$QTDCONTRATO40049_SEMANA_AQUITAR+
$QTDCONTRATO40050_SEMANA_AQUITAR+
$QTDCONTRATO40051_SEMANA_AQUITAR+
$QTDCONTRATO40052_SEMANA_AQUITAR+
$QTDCONTRATO40053_SEMANA_AQUITAR+
$QTDCONTRATO40054_SEMANA_AQUITAR+
$QTDCONTRATO40055_SEMANA_AQUITAR+
$QTDCONTRATO40056_SEMANA_AQUITAR+
$QTDCONTRATO40057_SEMANA_AQUITAR+
$QTDCONTRATO40058_SEMANA_AQUITAR+
$QTDCONTRATO40059_SEMANA_AQUITAR+
$QTDCONTRATO40060_SEMANA_AQUITAR+
$QTDCONTRATO40061_SEMANA_AQUITAR+
$QTDCONTRATO40062_SEMANA_AQUITAR+
$QTDCONTRATO40063_SEMANA_AQUITAR+
$QTDCONTRATO40064_SEMANA_AQUITAR+
$QTDCONTRATO40065_SEMANA_AQUITAR+
$QTDCONTRATO40066_SEMANA_AQUITAR+
$QTDCONTRATO40067_SEMANA_AQUITAR+
$QTDCONTRATO40068_SEMANA_AQUITAR+
$QTDCONTRATO40069_SEMANA_AQUITAR+
$QTDCONTRATO40070_SEMANA_AQUITAR+
$QTDCONTRATO40071_SEMANA_AQUITAR+
$QTDCONTRATO40072_SEMANA_AQUITAR+
$QTDCONTRATO40073_SEMANA_AQUITAR+
$QTDCONTRATO40074_SEMANA_AQUITAR+
$QTDCONTRATO40075_SEMANA_AQUITAR+
$QTDCONTRATO40076_SEMANA_AQUITAR+
$QTDCONTRATO40077_SEMANA_AQUITAR+
$QTDCONTRATO40078_SEMANA_AQUITAR+
$QTDCONTRATO40079_SEMANA_AQUITAR+
$QTDCONTRATO40080_SEMANA_AQUITAR;
//SELECT SUM(Qtd_conf) AS SQUANTIDADE FROM tb_ordem_venda WHERE col_TipoOV='Venda Representante' AND UM='10' AND SAFRA='5';



$SOMAQUANTIORDQUITADA = mysqli_query($CONNECTIONFATURAMENTO, "SELECT SUM(SAIDA.QUANTIDADE) AS SQUANTIDADE FROM tb_contratos AS CONTRATO LEFT JOIN tb_ordem_venda AS OV on CONTRATO.col_docvendas=OV.N_pedido LEFT JOIN tb_saida_semana AS SAIDA ON OV.Doc_SD=SAIDA.ORDEM WHERE OV.col_TipoOV='Venda Representante' AND OV.UM='10' AND CONTRATO.col_position BETWEEN '40000' AND '40099' AND SAIDA.SAFRA='$SAFRA' AND SAIDA.TRANSPORTADORA!='' ORDER BY `CONTRATO`.`col_nome` ASC;");
$COSULTORDQUIT = mysqli_num_rows($SOMAQUANTIORDQUITADA);
if($COSULTORDQUIT > 0){
    while ($Linha = $SOMAQUANTIORDQUITADA->fetch_array()){
        if ($row['UNIDADE']=='KG') {
            $QSAIDAFINALKG_SEMANA_AQUITAR = $Linha['SQUANTIDADE']/50;
        }else{
            $QSAIDAFINALSC_SEMANA_AQUITAR = $Linha['SQUANTIDADE'];
        }
    }
}

$RESULTADOQUITADASSAIDAS_SEMANA_AQUITAR = 
$QSAIDAFINALKG_SEMANA_AQUITAR+$QSAIDAFINALSC_SEMANA_AQUITAR;


$SALDO_SEMANA_AQUITAR = $RESULTADO_SEMANA_AQUITAR-$RESULTADOQUITADASSAIDAS_SEMANA_AQUITAR;

?>