<?php
$CONNECTIONINCLUDE = mysqli_connect('localhost','remoto','XTKfAFKPHNhWpSqW','sistemagsgfaturamento');
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$AnoCorrente-$Mes-01' and GRUPO_MERC='9410' AND DEPOSITO!='' AND SAFRA='$SafraAnual'  GROUP BY MATERIAL");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
		if($SQLINE['MATERIAL']=='100000'){
            $CRISTAL2ASCUM = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100001'){
            $CRISTAL2AKGUM = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100002'){
            $CRISTAL2ATOUM = $SQLINE['SMQUANTIDADE']*20;
		}
		if($SQLINE['MATERIAL']=='100140'){
            $CRISTALBONSUCROSCUM = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100141'){
            $CRISTALBONSUCROKGUM = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100014'){
            $VHPTOUM = $SQLINE['SMQUANTIDADE']*20;
		}
	}
}
$ACUCACRISTALUM = $CRISTAL2ASCUM+$CRISTAL2AKGUM+$CRISTAL2ATOUM;
$BOMSUCROCRISTUM = $CRISTALBONSUCROSCUM+$CRISTALBONSUCROKGUM;
/****************************************************************************************************************************************************/
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$AnoCorrente-$Mes-02' and GRUPO_MERC='9410' AND DEPOSITO!='' AND SAFRA='$SafraAnual'  GROUP BY MATERIAL");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
		if($SQLINE['MATERIAL']=='100000'){
            $CRISTAL2ASCDOIS = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100001'){
            $CRISTAL2AKGDOIS = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100002'){
            $CRISTAL2ATODOIS = $SQLINE['SMQUANTIDADE']*20;
		}
		if($SQLINE['MATERIAL']=='100140'){
            $CRISTALBONSUCROSCDOIS = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100141'){
            $CRISTALBONSUCROKGDOIS = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100014'){
            $VHPTODOIS = $SQLINE['SMQUANTIDADE']*20;
		}
	}
}
$ACUCACRISTALDOIS = $CRISTAL2ASCDOIS+$CRISTAL2AKGDOIS+$CRISTAL2ATODOIS;
$BOMSUCROCRISTDOIS = $CRISTALBONSUCROSCDOIS+$CRISTALBONSUCROKGDOIS;
/****************************************************************************************************************************************************/
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$AnoCorrente-$Mes-03' and GRUPO_MERC='9410' AND DEPOSITO!='' AND SAFRA='$SafraAnual'  GROUP BY MATERIAL");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
		if($SQLINE['MATERIAL']=='100000'){
            $CRISTAL2ASCTRES = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100001'){
            $CRISTAL2AKGTRES = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100002'){
            $CRISTAL2ATOTRES = $SQLINE['SMQUANTIDADE']*20;
		}
		if($SQLINE['MATERIAL']=='100140'){
            $CRISTALBONSUCROSCTRES = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100141'){
            $CRISTALBONSUCROKGTRES = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100014'){
            $VHPTOTRES = $SQLINE['SMQUANTIDADE']*20;
		}
	}
}
$ACUCACRISTALTRES = $CRISTAL2ASCTRES+$CRISTAL2AKGTRES+$CRISTAL2ATOTRES;
$BOMSUCROCRISTTRES = $CRISTALBONSUCROSCTRES+$CRISTALBONSUCROKGTRES;
/****************************************************************************************************************************************************/
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$AnoCorrente-$Mes-04' and GRUPO_MERC='9410' AND DEPOSITO!='' AND SAFRA='$SafraAnual'  GROUP BY MATERIAL");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
		if($SQLINE['MATERIAL']=='100000'){
            $CRISTAL2ASCQUATRO = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100001'){
            $CRISTAL2AKGQUATRO = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100002'){
            $CRISTAL2ATOQUATRO = $SQLINE['SMQUANTIDADE']*20;
		}
		if($SQLINE['MATERIAL']=='100140'){
            $CRISTALBONSUCROSCQUATRO = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100141'){
            $CRISTALBONSUCROKGQUATRO = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100014'){
            $VHPTOQUATRO = $SQLINE['SMQUANTIDADE']*20;
		}
	}
}
$ACUCACRISTALQUATRO = $CRISTAL2ASCQUATRO+$CRISTAL2AKGQUATRO+$CRISTAL2ATOQUATRO;
$BOMSUCROCRISTQUATRO = $CRISTALBONSUCROSCQUATRO+$CRISTALBONSUCROKGQUATRO;
/****************************************************************************************************************************************************/
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$AnoCorrente-$Mes-05' and GRUPO_MERC='9410' AND DEPOSITO!='' AND SAFRA='$SafraAnual'  GROUP BY MATERIAL");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
		if($SQLINE['MATERIAL']=='100000'){
            $CRISTAL2ASCCINCO = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100001'){
            $CRISTAL2AKGCINCO = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100002'){
            $CRISTAL2ATOCINCO = $SQLINE['SMQUANTIDADE']*20;
		}
		if($SQLINE['MATERIAL']=='100140'){
            $CRISTALBONSUCROSCCINCO = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100141'){
            $CRISTALBONSUCROKGCINCO = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100014'){
            $VHPTOCINCO = $SQLINE['SMQUANTIDADE']*20;
		}
	}
}
$ACUCACRISTALCINCO = $CRISTAL2ASCCINCO+$CRISTAL2AKGCINCO+$CRISTAL2ATOCINCO;
$BOMSUCROCRISTCINCO = $CRISTALBONSUCROSCCINCO+$CRISTALBONSUCROKGCINCO;
/****************************************************************************************************************************************************/
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$AnoCorrente-$Mes-06' and GRUPO_MERC='9410' AND DEPOSITO!='' AND SAFRA='$SafraAnual'  GROUP BY MATERIAL");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
		if($SQLINE['MATERIAL']=='100000'){
            $CRISTAL2ASCSEIS = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100001'){
            $CRISTAL2AKGSEIS = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100002'){
            $CRISTAL2ATOSEIS = $SQLINE['SMQUANTIDADE']*20;
		}
		if($SQLINE['MATERIAL']=='100140'){
            $CRISTALBONSUCROSCSEIS = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100141'){
            $CRISTALBONSUCROKGSEIS = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100014'){
            $VHPTOSEIS = $SQLINE['SMQUANTIDADE']*20;
		}
	}
}
$ACUCACRISTALSEIS = $CRISTAL2ASCSEIS+$CRISTAL2AKGSEIS+$CRISTAL2ATOSEIS;
$BOMSUCROCRISTSEIS = $CRISTALBONSUCROSCSEIS+$CRISTALBONSUCROKGSEIS;
/****************************************************************************************************************************************************/
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$AnoCorrente-$Mes-07' and GRUPO_MERC='9410' AND DEPOSITO!='' AND SAFRA='$SafraAnual'  GROUP BY MATERIAL");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
		if($SQLINE['MATERIAL']=='100000'){
            $CRISTAL2ASCSETE = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100001'){
            $CRISTAL2AKGSETE = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100002'){
            $CRISTAL2ATOSETE = $SQLINE['SMQUANTIDADE']*20;
		}
		if($SQLINE['MATERIAL']=='100140'){
            $CRISTALBONSUCROSCSETE = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100141'){
            $CRISTALBONSUCROKGSETE = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100014'){
            $VHPTOSETE = $SQLINE['SMQUANTIDADE']*20;
		}
	}
}
$ACUCACRISTALSETE = $CRISTAL2ASCSETE+$CRISTAL2AKGSETE+$CRISTAL2ATOSETE;
$BOMSUCROCRISTSETE = $CRISTALBONSUCROSCSETE+$CRISTALBONSUCROKGSETE;
/****************************************************************************************************************************************************/
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$AnoCorrente-$Mes-08' and GRUPO_MERC='9410' AND DEPOSITO!='' AND SAFRA='$SafraAnual'  GROUP BY MATERIAL");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
		if($SQLINE['MATERIAL']=='100000'){
            $CRISTAL2ASCOITO = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100001'){
            $CRISTAL2AKGOITO = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100002'){
            $CRISTAL2ATOOITO = $SQLINE['SMQUANTIDADE']*20;
		}
		if($SQLINE['MATERIAL']=='100140'){
            $CRISTALBONSUCROSCOITO = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100141'){
            $CRISTALBONSUCROKGOITO = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100014'){
            $VHPTOOITO = $SQLINE['SMQUANTIDADE']*20;
		}
	}
}
$ACUCACRISTALOITO = $CRISTAL2ASCOITO+$CRISTAL2AKGOITO+$CRISTAL2ATOOITO;
$BOMSUCROCRISTOITO = $CRISTALBONSUCROSCOITO+$CRISTALBONSUCROKGOITO;
/****************************************************************************************************************************************************/
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$AnoCorrente-$Mes-09' and GRUPO_MERC='9410' AND DEPOSITO!='' AND SAFRA='$SafraAnual'  GROUP BY MATERIAL");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
		if($SQLINE['MATERIAL']=='100000'){
            $CRISTAL2ASCNOVE = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100001'){
            $CRISTAL2AKGNOVE = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100002'){
            $CRISTAL2ATONOVE = $SQLINE['SMQUANTIDADE']*20;
		}
		if($SQLINE['MATERIAL']=='100140'){
            $CRISTALBONSUCROSCNOVE = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100141'){
            $CRISTALBONSUCROKGNOVE = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100014'){
            $VHPTONOVE = $SQLINE['SMQUANTIDADE']*20;
		}
	}
}
$ACUCACRISTALNOVE = $CRISTAL2ASCNOVE+$CRISTAL2AKGNOVE+$CRISTAL2ATONOVE;
$BOMSUCROCRISTNOVE = $CRISTALBONSUCROSCNOVE+$CRISTALBONSUCROKGNOVE;
/****************************************************************************************************************************************************/
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$AnoCorrente-$Mes-10' and GRUPO_MERC='9410' AND DEPOSITO!='' AND SAFRA='$SafraAnual'  GROUP BY MATERIAL");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
		if($SQLINE['MATERIAL']=='100000'){
            $CRISTAL2ASCDEZ = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100001'){
            $CRISTAL2AKGDEZ = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100002'){
            $CRISTAL2ATODEZ = $SQLINE['SMQUANTIDADE']*20;
		}
		if($SQLINE['MATERIAL']=='100140'){
            $CRISTALBONSUCROSCDEZ = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100141'){
            $CRISTALBONSUCROKGDEZ = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100014'){
            $VHPTODEZ = $SQLINE['SMQUANTIDADE']*20;
		}
	}
}
$ACUCACRISTALDEZ = $CRISTAL2ASCDEZ+$CRISTAL2AKGDEZ+$CRISTAL2ATODEZ;
$BOMSUCROCRISTDEZ = $CRISTALBONSUCROSCDEZ+$CRISTALBONSUCROKGDEZ;
/****************************************************************************************************************************************************/
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$AnoCorrente-$Mes-11' and GRUPO_MERC='9410' AND DEPOSITO!='' AND SAFRA='$SafraAnual'  GROUP BY MATERIAL");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
		if($SQLINE['MATERIAL']=='100000'){
            $CRISTAL2ASCONZE = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100001'){
            $CRISTAL2AKGONZE = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100002'){
            $CRISTAL2ATOONZE = $SQLINE['SMQUANTIDADE']*20;
		}
		if($SQLINE['MATERIAL']=='100140'){
            $CRISTALBONSUCROSCONZE = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100141'){
            $CRISTALBONSUCROKGONZE = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100014'){
            $VHPTOONZE = $SQLINE['SMQUANTIDADE']*20;
		}
	}
}
$ACUCACRISTALONZE = $CRISTAL2ASCONZE+$CRISTAL2AKGONZE+$CRISTAL2ATOONZE;
$BOMSUCROCRISTONZE = $CRISTALBONSUCROSCONZE+$CRISTALBONSUCROKGONZE;
/****************************************************************************************************************************************************/
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$AnoCorrente-$Mes-12' and GRUPO_MERC='9410' AND DEPOSITO!='' AND SAFRA='$SafraAnual'  GROUP BY MATERIAL");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
		if($SQLINE['MATERIAL']=='100000'){
            $CRISTAL2ASCDOZE = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100001'){
            $CRISTAL2AKGDOZE = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100002'){
            $CRISTAL2ATODOZE = $SQLINE['SMQUANTIDADE']*20;
		}
		if($SQLINE['MATERIAL']=='100140'){
            $CRISTALBONSUCROSCDOZE = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100141'){
            $CRISTALBONSUCROKGDOZE = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100014'){
            $VHPTODOZE = $SQLINE['SMQUANTIDADE']*20;
		}
	}
}
$ACUCACRISTALDOZE = $CRISTAL2ASCDOZE+$CRISTAL2AKGDOZE+$CRISTAL2ATODOZE;
$BOMSUCROCRISTDOZE = $CRISTALBONSUCROSCDOZE+$CRISTALBONSUCROKGDOZE;
/****************************************************************************************************************************************************/
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$AnoCorrente-$Mes-13' and GRUPO_MERC='9410' AND DEPOSITO!='' AND SAFRA='$SafraAnual'  GROUP BY MATERIAL");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
		if($SQLINE['MATERIAL']=='100000'){
            $CRISTAL2ASCTREZE = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100001'){
            $CRISTAL2AKGTREZE = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100002'){
            $CRISTAL2ATOTREZE = $SQLINE['SMQUANTIDADE']*20;
		}
		if($SQLINE['MATERIAL']=='100140'){
            $CRISTALBONSUCROSCTREZE = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100141'){
            $CRISTALBONSUCROKGTREZE = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100014'){
            $VHPTOTREZE = $SQLINE['SMQUANTIDADE']*20;
		}
	}
}
$ACUCACRISTALTREZE = $CRISTAL2ASCTREZE+$CRISTAL2AKGTREZE+$CRISTAL2ATOTREZE;
$BOMSUCROCRISTTREZE = $CRISTALBONSUCROSCTREZE+$CRISTALBONSUCROKGTREZE;
/****************************************************************************************************************************************************/
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$AnoCorrente-$Mes-14' and GRUPO_MERC='9410' AND DEPOSITO!='' AND SAFRA='$SafraAnual'  GROUP BY MATERIAL");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
		if($SQLINE['MATERIAL']=='100000'){
            $CRISTAL2ASCQUATORZE = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100001'){
            $CRISTAL2AKGQUATORZE = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100002'){
            $CRISTAL2ATOQUATORZE = $SQLINE['SMQUANTIDADE']*20;
		}
		if($SQLINE['MATERIAL']=='100140'){
            $CRISTALBONSUCROSCQUATORZE = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100141'){
            $CRISTALBONSUCROKGQUATORZE = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100014'){
            $VHPTOQUATORZE = $SQLINE['SMQUANTIDADE']*20;
		}
	}
}
$ACUCACRISTALQUATORZE = $CRISTAL2ASCQUATORZE+$CRISTAL2AKGQUATORZE+$CRISTAL2ATOQUATORZE;
$BOMSUCROCRISTQUATORZE = $CRISTALBONSUCROSCQUATORZE+$CRISTALBONSUCROKGQUATORZE;
/****************************************************************************************************************************************************/
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$AnoCorrente-$Mes-15' and GRUPO_MERC='9410' AND DEPOSITO!='' AND SAFRA='$SafraAnual'  GROUP BY MATERIAL");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
		if($SQLINE['MATERIAL']=='100000'){
            $CRISTAL2ASCQUINZE = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100001'){
            $CRISTAL2AKGQUINZE = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100002'){
            $CRISTAL2ATOQUINZE = $SQLINE['SMQUANTIDADE']*20;
		}
		if($SQLINE['MATERIAL']=='100140'){
            $CRISTALBONSUCROSCQUINZE = $SQLINE['SMQUANTIDADE'];
		}
		if($SQLINE['MATERIAL']=='100141'){
            $CRISTALBONSUCROKGQUINZE = $SQLINE['SMQUANTIDADE']/50;
		}
		if($SQLINE['MATERIAL']=='100014'){
            $VHPTOQUINZE = $SQLINE['SMQUANTIDADE']*20;
		}
	}
}
$ACUCACRISTALQUINZE = $CRISTAL2ASCQUINZE+$CRISTAL2AKGQUINZE+$CRISTAL2ATOQUINZE;
$BOMSUCROCRISTQUINZE = $CRISTALBONSUCROSCQUINZE+$CRISTALBONSUCROKGQUINZE;

?>
