<?php
$ALCOOL = mysqli_query($CONNECTIONINCLUDE, "SELECT *,SUM(QUANTIDADE) AS SOMAQUANTIDADE,SUM(VL_BRUTO) AS SOMABRUTO FROM `tb_saida_semana` WHERE DATA_EMISS BETWEEN '$TO_BORN' AND '$TO_END' AND GRUPO_MERC='9420' AND TIPO_ORDEM	!='ZVVF'  AND MATERIAL!='100017' GROUP BY CIDADE,COD_RECEB ORDER BY COD_RECEB");
$CONSULTAALCOOL = mysqli_num_rows($ALCOOL);


$HIDRATADO = mysqli_query($CONNECTIONINCLUDE, "SELECT *,SUM(QUANTIDADE) AS SOMAQUANTIDADE,SUM(VL_BRUTO) AS SOMABRUTO FROM `tb_saida_semana` WHERE DATA_EMISS BETWEEN '$TO_BORN' AND '$TO_END' AND GRUPO_MERC='9420' AND TIPO_ORDEM!='ZVVF' AND MATERIAL='100017' GROUP BY CIDADE,COD_RECEB ORDER BY COD_RECEB");
$CONSULTAALCOOLHIDRATADO = mysqli_num_rows($HIDRATADO);

$SQLALCOOL = mysqli_query($CONNECTIONINCLUDE, "SELECT *,SUM(QUANTIDADE) AS SOMAQUANTIDADE, SUM(VL_BRUTO) AS SOMABRUTO FROM `tb_saida_semana` WHERE DATA_EMISS BETWEEN '$TO_BORN' AND '$TO_END' AND GRUPO_MERC='9420' AND TIPO_ORDEM!='ZVVF' ORDER BY COD_RECEB");
$ROWALCOOL = mysqli_num_rows($SQLALCOOL);
if ($ROWALCOOL > 0){
	while($SQLINE = mysqli_fetch_array($SQLALCOOL)){
        $TOTALQUANTIDADEALCOOL = $SQLINE['SOMAQUANTIDADE'];
        $TOTALVALORBRUTOALCOOL = $SQLINE['SOMABRUTO'];
	}
}
?>