<?php
/*******************************************************************************************/
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$TO_BORN' and GRUPO_MERC='9410' AND DEPOSITO!='' AND TRANSPORTADORA!='' GROUP BY UNIDADE");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
        if($SQLINE['UNIDADE']=='KG'){
            $SEGUNDASCSAC = $SQLINE['SMQUANTIDADE']/50;
        }
        if($SQLINE['UNIDADE']=='SC'){
            $SEGUNDASCSAC1 = $SQLINE['SMQUANTIDADE'];
        }
        if($SQLINE['UNIDADE']=='TON'){
            $SEGUNDASCSAC2 = $SQLINE['SMQUANTIDADE']*20;
        }
        if($SQLINE['UNIDADE']=='TM' && $SQLINE['MATERIAL']!='100014' && $SQLINE['MATERIAL']!='100035' && $SQLINE['MATERIAL']!='100145' && $SQLINE['MATERIAL']!='100180'){
            $SEGUNDASCSAC3 = $SQLINE['SMQUANTIDADE']*20;
        }
        if($SQLINE['MATERIAL']=='100014'){
            $SEGUNDAFEIRAVHPACUCAR = $SQLINE['SMQUANTIDADE']*20;
        }
	}
}
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,CFOP,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS='$TO_BORN' GROUP BY CFOP");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
        if($SQLINE['CFOP']=='5910/AA'){
            $SEGUNDAFEIRACFOPACUCAR = $SQLINE['SMQUANTIDADE'];
        }
	}
}
$SEGUNDAFEIRAACUCAR = $SEGUNDASCSAC+$SEGUNDASCSAC1+$SEGUNDASCSAC2+$SEGUNDASCSAC3+$SEGUNDAFEIRACFOPACUCAR;


$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS=DATE_ADD('$TO_BORN' , INTERVAL 1 DAY) and GRUPO_MERC='9410' AND DEPOSITO!=''  GROUP BY UNIDADE");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
        if($SQLINE['UNIDADE']=='KG'){
            $TERCASCSAC = $SQLINE['SMQUANTIDADE']/50;
        }
        if($SQLINE['UNIDADE']=='SC' && $SQLINE['TIPO_EMB']!=''){
            $TERCASCSAC1 = $SQLINE['SMQUANTIDADE'];
        }
        if($SQLINE['UNIDADE']=='TON'){
            $TERCASCSAC2 = $SQLINE['SMQUANTIDADE']*20;
        }
        if($SQLINE['UNIDADE']=='TM' && $SQLINE['MATERIAL']!='100014' && $SQLINE['MATERIAL']!='100035' && $SQLINE['MATERIAL']!='100145' && $SQLINE['MATERIAL']!='100180'){
            $TERCASCSAC3 = $SQLINE['SMQUANTIDADE']*20;
        }
        if($SQLINE['MATERIAL']=='100014'){
            $TERÇAFEIRAVHPACUCAR = $SQLINE['SMQUANTIDADE']*20;
        }
	}
}
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,CFOP,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS=DATE_ADD('$TO_BORN' , INTERVAL 1 DAY) GROUP BY CFOP");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
        if($SQLINE['CFOP']=='5910/AA'){
            $TERÇAFEIRACFOPACUCAR = $SQLINE['SMQUANTIDADE'];
        }
	}
}
$TERÇAFEIRAACUCAR = $TERCASCSAC+$TERCASCSAC1+$TERCASCSAC2+$TERCASCSAC3+$TERÇAFEIRACFOPACUCAR;

$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS=DATE_ADD('$TO_BORN' , INTERVAL 2 DAY) and GRUPO_MERC='9410' AND DEPOSITO!=''  GROUP BY UNIDADE");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
        if($SQLINE['UNIDADE']=='KG'){
            $QUARTASCSAC = $SQLINE['SMQUANTIDADE']/50;
        }
        if($SQLINE['UNIDADE']=='SC'){
            $QUARTASCSAC1 = $SQLINE['SMQUANTIDADE'];
        }
        if($SQLINE['UNIDADE']=='TON'){
            $QUARTASCSAC2 = $SQLINE['SMQUANTIDADE']*20;
        }
        if($SQLINE['UNIDADE']=='TM' && $SQLINE['MATERIAL']!='100014' && $SQLINE['MATERIAL']!='100035' && $SQLINE['MATERIAL']!='100145' && $SQLINE['MATERIAL']!='100180'){
            $QUARTASCSAC3 = $SQLINE['SMQUANTIDADE']*20;
        }
        if($SQLINE['MATERIAL']=='100014'){
            $QUARTAFEIRAVHPACUCAR = $SQLINE['SMQUANTIDADE']*20;
        }
	}
}
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,CFOP,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS=DATE_ADD('$TO_BORN' , INTERVAL 2 DAY) GROUP BY CFOP");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
        if($SQLINE['CFOP']=='5910/AA'){
            $QUARTAFEIRACFOPACUCAR = $SQLINE['SMQUANTIDADE'];
        }
	}
}
$QUARTAFEIRAACUCAR = $QUARTASCSAC+$QUARTASCSAC1+$QUARTASCSAC2+$QUARTASCSAC3+$QUARTAFEIRACFOPACUCAR;

$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS=DATE_ADD('$TO_BORN' , INTERVAL 3 DAY) and GRUPO_MERC='9410' AND DEPOSITO!='' GROUP BY UNIDADE");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
        if($SQLINE['UNIDADE']=='KG'){
            $QUINTASCSAC = $SQLINE['SMQUANTIDADE']/50;
        }
        if($SQLINE['UNIDADE']=='SC'){
            $QUINTASCSAC1 = $SQLINE['SMQUANTIDADE'];
        }
        if($SQLINE['UNIDADE']=='TON'){
            $QUINTASCSAC2 = $SQLINE['SMQUANTIDADE']*20;
        }
        if($SQLINE['UNIDADE']=='TM' && $SQLINE['MATERIAL']!='100014' && $SQLINE['MATERIAL']!='100035' && $SQLINE['MATERIAL']!='100145' && $SQLINE['MATERIAL']!='100180'){
            $QUINTASCSAC3 = $SQLINE['SMQUANTIDADE']*20;
        }
        if($SQLINE['MATERIAL']=='100014'){
            $QUINTAFEIRAVHPACUCAR = $SQLINE['SMQUANTIDADE']*20;
        }
	}
}
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,CFOP,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS=DATE_ADD('$TO_BORN' , INTERVAL 3 DAY) GROUP BY CFOP");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
        if($SQLINE['CFOP']=='5910/AA'){
            $QUINTAFEIRACFOPACUCAR = $SQLINE['SMQUANTIDADE'];
        }
	}
}
$QUINTAFEIRAACUCAR = $QUINTASCSAC+$QUINTASCSAC1+$QUINTASCSAC2+$QUINTASCSAC3+$QUINTAFEIRACFOPACUCAR;

$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS=DATE_ADD('$TO_BORN' , INTERVAL 4 DAY) and GRUPO_MERC='9410' AND DEPOSITO!=''  GROUP BY UNIDADE");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
        if($SQLINE['UNIDADE']=='KG'){
            $SEXTASCSAC = $SQLINE['SMQUANTIDADE']/50;
        }
        if($SQLINE['UNIDADE']=='SC'){
            $SEXTASCSAC1 = $SQLINE['SMQUANTIDADE'];
        }
        if($SQLINE['UNIDADE']=='TON'){
            $SEXTASCSAC2 = $SQLINE['SMQUANTIDADE']*20;
        }
        if($SQLINE['UNIDADE']=='TM' && $SQLINE['MATERIAL']!='100014' && $SQLINE['MATERIAL']!='100035' && $SQLINE['MATERIAL']!='100145' && $SQLINE['MATERIAL']!='100180'){
            $SEXTASCSAC3 = $SQLINE['SMQUANTIDADE']*20;
        }
        if($SQLINE['MATERIAL']=='100014'){
            $SEXTAFEIRAVHPACUCAR = $SQLINE['SMQUANTIDADE']*20;
        }
	}
}
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,CFOP,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS=DATE_ADD('$TO_BORN' , INTERVAL 4 DAY) GROUP BY CFOP");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
        if($SQLINE['CFOP']=='5910/AA'){
            $SEXTAFEIRACFOPACUCAR = $SQLINE['SMQUANTIDADE'];
        }
	}
}
$SEXTAFEIRAACUCAR = $SEXTASCSAC+$SEXTASCSAC1+$SEXTASCSAC2+$SEXTASCSAC3+$SEXTAFEIRACFOPACUCAR;

$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS=DATE_ADD('$TO_BORN' , INTERVAL 5 DAY) and GRUPO_MERC='9410' AND DEPOSITO!=''  GROUP BY UNIDADE");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
        if($SQLINE['UNIDADE']=='KG'){
            $SABADOSCSAC = $SQLINE['SMQUANTIDADE']/50;
        }
        if($SQLINE['UNIDADE']=='SC'){
            $SABADOSCSAC1 = $SQLINE['SMQUANTIDADE'];
        }
        if($SQLINE['UNIDADE']=='TON'){
            $SABADOSCSAC2 = $SQLINE['SMQUANTIDADE']*20;
        }
        if($SQLINE['UNIDADE']=='TM' && $SQLINE['MATERIAL']!='100014' && $SQLINE['MATERIAL']!='100035' && $SQLINE['MATERIAL']!='100145' && $SQLINE['MATERIAL']!='100180'){
            $SABADOSCSAC3 = $SQLINE['SMQUANTIDADE']*20;
        }
        if($SQLINE['MATERIAL']=='100014'){
            $SABADOVHPACUCAR = $SQLINE['SMQUANTIDADE']*20;
        }
	}
}
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,CFOP,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS=DATE_ADD('$TO_BORN' , INTERVAL 5 DAY) GROUP BY CFOP");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
        if($SQLINE['CFOP']=='5910/AA'){
            $SABADOCFOPACUCAR = $SQLINE['SMQUANTIDADE'];
        }
	}
}
$SABADOACUCAR = $SABADOSCSAC+$SABADOSCSAC1+$SABADOSCSAC2+$SABADOSCSAC3+$SABADOCFOPACUCAR;

$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,TIPO_EMB,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS=DATE_ADD('$TO_BORN' , INTERVAL 6 DAY) and GRUPO_MERC='9410' AND DEPOSITO!=''  GROUP BY UNIDADE");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
        if($SQLINE['UNIDADE']=='KG'){
            $DOMINGOSCSAC = $SQLINE['SMQUANTIDADE']/50;
        }
        if($SQLINE['UNIDADE']=='SC'){
            $DOMINGOSCSAC1 = $SQLINE['SMQUANTIDADE'];
        }
        if($SQLINE['UNIDADE']=='TON'){
            $DOMINGOSCSAC2 = $SQLINE['SMQUANTIDADE']*20;
        }
        if($SQLINE['UNIDADE']=='TM' && $SQLINE['MATERIAL']!='100014' && $SQLINE['MATERIAL']!='100035' && $SQLINE['MATERIAL']!='100145' && $SQLINE['MATERIAL']!='100180'){
            $DOMINGOSCSAC3 = $SQLINE['SMQUANTIDADE']*20;
        }
        if($SQLINE['MATERIAL']=='100014'){
            $DOMINGOVHPACUCAR = $SQLINE['SMQUANTIDADE']*20;
        }
	}
}
$QUERYCRISTAL = mysqli_query($CONNECTIONINCLUDE, "SELECT UNIDADE,MATERIAL,CFOP,SUM(QUANTIDADE) AS SMQUANTIDADE FROM `tb_saida_semana` WHERE DATA_EMISS=DATE_ADD('$TO_BORN' , INTERVAL 6 DAY) GROUP BY CFOP");
$ROWADIACRISTAL = mysqli_num_rows($QUERYCRISTAL);
if ($ROWADIACRISTAL > 0){
	while($SQLINE = mysqli_fetch_array($QUERYCRISTAL)){
        if($SQLINE['CFOP']=='5910/AA'){
            $DOMINGOCFOPACUCAR = $SQLINE['SMQUANTIDADE'];
        }
	}
}
$DOMINGOACUCAR = $DOMINGOSCSAC+$DOMINGOSCSAC1+$DOMINGOSCSAC2+$DOMINGOSCSAC3+$DOMINGOCFOPACUCAR;


$TOTALCRISTAL = $SEGUNDAFEIRAACUCAR + $TERÇAFEIRAACUCAR + $QUARTAFEIRAACUCAR + $QUINTAFEIRAACUCAR + $SEXTAFEIRAACUCAR + $SABADOACUCAR + $DOMINGOACUCAR;
$TOTALVHP = $SEGUNDAFEIRAVHPACUCAR + $TERÇAFEIRAVHPACUCAR + $QUARTAFEIRAVHPACUCAR + $QUINTAFEIRAVHPACUCAR + $SEXTAFEIRAVHPACUCAR + $SABADOVHPACUCAR + $DOMINGOVHPACUCAR;

?>